const B='http://localhost:3000/api';
const call=async(tok,m,u,b)=>{const r=await fetch(B+u,{method:m,headers:{'content-type':'application/json',authorization:'Bearer '+tok},body:b?JSON.stringify(b):undefined});let j;try{j=await r.json()}catch{};return {s:r.status,j}};
const login=async(i,p)=>(await (await fetch(B+'/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identifier:i,password:p,deviceId:'dev-'+i,deviceName:'t',platform:'WEB'})})).json()).accessToken;
let fail=0; const ok=(n,c,x)=>{console.log((c?'PASS':'FAIL')+' '+n+(c?'':' '+JSON.stringify(x)));if(!c)fail++};
const A=await login('9999999999','ChangeMe@123'), F=await login('9999999998','Demo@12345'), S=await login('9999999997','Demo@12345');
const subs=(await call(A,'GET','/subjects')).j; const topic=await call(A,'POST','/topics',{subjectId:subs[0].id,name:'T'+Date.now()}); ok('topic create',topic.s===201,topic);
const mk=(t,opts,type)=>({topicId:topic.j.id,text:t,type,options:opts.map((o,i)=>({text:'o'+i,isCorrect:o}))});
const bad=await call(F,'POST','/questions',mk('bad',[true,true],'SINGLE')); ok('single w/ 2 correct rejected',bad.s===400,bad);
const bad2=await call(F,'POST','/questions',mk('bad',[false,false])); ok('no correct rejected',bad2.s===400,bad2);
const sf=await call(S,'GET','/questions'); ok('student blocked from bank',sf.s===403,sf);
const q1=await call(F,'POST','/questions',mk('Q1',[true,false,false,false])); const q2=await call(F,'POST','/questions',mk('Q2',[true,true,false],'MULTIPLE')); const q3=await call(F,'POST','/questions',mk('Q3',[false,true]));
ok('3 questions created',[q1,q2,q3].every(x=>x.s===201),[q1,q2,q3].map(x=>x.s));
const batches=(await call(A,'GET','/batches')).j.items; const demo=batches.find(b=>b.name==='Demo Batch 2026');
const t=await call(F,'POST','/tests',{title:'E2E test',durationMin:30,negativeMark:1}); ok('test create (faculty)',t.s===201,t);
const tid=t.j.id;
const pubEmpty=await call(F,'POST',`/tests/${tid}/publish`); ok('publish empty rejected',pubEmpty.s===400,pubEmpty);
const sq=await call(F,'PUT',`/tests/${tid}/questions`,{questions:[{questionId:q1.j.id,marks:4},{questionId:q2.j.id,marks:4},{questionId:q3.j.id,marks:4}]}); ok('set questions, total=12',sq.s===200&&Number(sq.j.totalMarks)===12,sq);
const sb=await call(F,'PUT',`/tests/${tid}/batches`,{batchIds:[demo.id]}); ok('set batches',sb.s===200,sb);
const pub=await call(F,'POST',`/tests/${tid}/publish`); ok('publish',pub.s===201||pub.s===200,pub);
const av=await call(S,'GET','/my/tests'); const mine=av.j.find(x=>x.id===tid); ok('student sees test OPEN',mine&&mine.state==='OPEN',av);
const st=await call(S,'POST',`/my/tests/${tid}/start`); ok('start',st.s===201,st);
const paper=st.j; ok('paper has no isCorrect',!JSON.stringify(paper).includes('isCorrect'),null);
const aid=paper.attemptId;
const again=await call(S,'POST',`/my/tests/${tid}/start`); ok('resume returns same attempt',again.j.attemptId===aid,again);
const O=id=>paper.questions.find(q=>q.id===id).options;
// right answers by option index: q1 o0 ; q2 o0,o1 ; q3 o1 -> answer q1 right, q2 wrong, q3 skipped => 4-1=3
const byText=(qid,t)=>O(qid).find(o=>o.text===t).id;
const sv=await call(S,'PUT',`/attempts/${aid}/answers`,{answers:[{questionId:q1.j.id,selectedOptionIds:[byText(q1.j.id,'o0')]},{questionId:q2.j.id,selectedOptionIds:[byText(q2.j.id,'o0')]}]}); ok('autosave',sv.s===200,sv);
const multiBad=await call(S,'PUT',`/attempts/${aid}/answers`,{answers:[{questionId:q1.j.id,selectedOptionIds:[byText(q1.j.id,'o0'),byText(q1.j.id,'o1')]}]}); ok('2 options on SINGLE rejected',multiBad.s===400,multiBad);
await call(S,'POST',`/attempts/${aid}/background`);
const early=await call(S,'GET',`/attempts/${aid}/result`); ok('result blocked while in progress',early.s===409,early);
const sub=await call(S,'POST',`/attempts/${aid}/submit`); ok('submit score=3 (4 -1 neg)',sub.s===201&&sub.j.score===3&&sub.j.correct===1&&sub.j.incorrect===1&&sub.j.unanswered===1,sub.j);
ok('review hidden while window open',sub.j.review===null,sub.j.review);
const re=await call(S,'POST',`/my/tests/${tid}/start`); ok('re-attempt blocked',re.s===409,re);
const late=await call(S,'PUT',`/attempts/${aid}/answers`,{answers:[]}); ok('save after submit blocked',late.s===409,late);
const res=await call(F,'GET',`/tests/${tid}/results`); ok('leaderboard',res.s===200&&res.j.rows.length===1&&res.j.rows[0].backgroundHits===1&&res.j.rows[0].rank===1,res.j);
const edit=await call(F,'PUT',`/tests/${tid}/questions`,{questions:[]}); ok('edit after attempts blocked',edit.s===403,edit);
const cl=await call(F,'POST',`/tests/${tid}/close`); ok('close',cl.s===201||cl.s===200,cl);
const rev=await call(S,'GET',`/attempts/${aid}/result`); ok('review open after close, has correct flags',rev.j.review&&rev.j.review.length===3&&JSON.stringify(rev.j.review).includes('"isCorrect":true'),rev.j);
const upd=await call(F,'PATCH',`/questions/${q1.j.id}`,{options:[{text:'a',isCorrect:true},{text:'b',isCorrect:false}]}); ok('edit answered question options blocked',upd.s===409,upd);
console.log(fail?`\n${fail} FAILED`:'\nALL PASSED'); process.exit(fail?1:0);
