// Demo content for prisma/demo-data.ts: courses, an Ayurveda question bank, notes and doubt threads.
// Facts follow the classical texts as commonly taught for BAMS / AIAPGET / AMO.

export type Diff = 'EASY' | 'MEDIUM' | 'HARD';
/** [topic, question, options, index of the correct option, difficulty, explanation] */
export type Q = [string, string, [string, string, string, string], 0 | 1 | 2 | 3, Diff, string];

export const QUESTIONS: Record<string, Q[]> = {
  'Padartha Vigyan': [
    ['Padartha', 'How many Padarthas are described by Acharya Charaka?', ['5', '6', '7', '9'], 1, 'EASY', 'Charaka lists six: Samanya, Vishesha, Guna, Dravya, Karma and Samavaya.'],
    ['Padartha', 'Which Padartha is added as the seventh by later Vaisheshika scholars?', ['Abhava', 'Shakti', 'Satta', 'Kala'], 0, 'MEDIUM', 'Later Vaisheshika works add Abhava (non-existence) to the six Bhava Padarthas.'],
    ['Dravya', 'How many Karana Dravyas are described?', ['5', '7', '9', '11'], 2, 'EASY', 'Pancha Mahabhuta, Atma, Manas, Kala and Dik: nine Karana Dravyas.'],
    ['Guna', 'How many Gurvadi Gunas are there?', ['10', '20', '41', '6'], 1, 'EASY', 'Twenty Gurvadi (Sharira) Gunas in ten opposite pairs.'],
    ['Guna', 'How many Paradi Gunas are described by Charaka?', ['6', '8', '10', '12'], 2, 'MEDIUM', 'Para, Apara, Yukti, Sankhya, Samyoga, Vibhaga, Prithaktva, Parimana, Samskara and Abhyasa.'],
    ['Guna', 'What is the total number of Gunas according to Charaka?', ['24', '36', '41', '20'], 2, 'MEDIUM', '20 Gurvadi + 10 Paradi + 5 Vishesha (Artha) + 6 Adhyatma Gunas = 41.'],
    ['Pramana', 'How many Pramanas are accepted by Charaka for examination (Pariksha)?', ['2', '3', '4', '8'], 2, 'EASY', 'Aptopadesha, Pratyaksha, Anumana and Yukti.'],
    ['Pramana', 'Yukti Pramana is a special contribution of which Acharya?', ['Sushruta', 'Charaka', 'Vagbhata', 'Kashyapa'], 1, 'MEDIUM', 'Yukti as a separate Pramana is described in Charaka Sutrasthana 11.'],
    ['Karya-Karana', 'Satkaryavada is the theory of which Darshana?', ['Nyaya', 'Vaisheshika', 'Sankhya', 'Charvaka'], 2, 'MEDIUM', 'Sankhya holds that the effect already exists in the cause (Satkaryavada).'],
    ['Karya-Karana', 'Pilupaka Vada belongs to which Darshana?', ['Nyaya', 'Vaisheshika', 'Mimamsa', 'Yoga'], 1, 'HARD', 'Vaisheshika explains change by heat acting on atoms (Pilu). Nyaya holds Pitharapaka.'],
    ['Dravya', 'According to Sankhya, how many Indriyas are there?', ['5', '10', '11', '13'], 2, 'MEDIUM', 'Five Jnanendriyas, five Karmendriyas and Manas as the Ubhayendriya.'],
    ['Padartha', 'Trisutra Ayurveda consists of', ['Vata, Pitta, Kapha', 'Hetu, Linga, Aushadha', 'Ahara, Nidra, Brahmacharya', 'Satva, Atma, Sharira'], 1, 'EASY', 'Hetu (cause), Linga (signs) and Aushadha (medicine) are the three sutras of Ayurveda.'],
  ],
  'Kriya Sharir': [
    ['Vata Dosha', 'What is the main seat (Sthana) of Prana Vayu?', ['Hridaya', 'Murdha', 'Nabhi', 'Guda'], 1, 'EASY', 'Prana Vayu resides in the Murdha (head).'],
    ['Pitta Dosha', 'Where is Pachaka Pitta located?', ['Hridaya', 'Twak', 'Between Amashaya and Pakvashaya', 'Netra'], 2, 'EASY', 'Pachaka Pitta lies between the Amashaya and Pakvashaya (Grahani region) and digests food.'],
    ['Pitta Dosha', 'Alochaka Pitta is located in the', ['Hridaya', 'Netra', 'Twak', 'Yakrit'], 1, 'EASY', 'Alochaka Pitta in the eyes is responsible for vision.'],
    ['Pitta Dosha', 'Bhrajaka Pitta is located in the', ['Twak', 'Hridaya', 'Netra', 'Amashaya'], 0, 'EASY', 'Bhrajaka Pitta in the skin gives lustre and digests applied substances.'],
    ['Pitta Dosha', 'Sadhaka Pitta is located in the', ['Murdha', 'Hridaya', 'Twak', 'Grahani'], 1, 'MEDIUM', 'Sadhaka Pitta in the Hridaya supports intellect, memory and ambition.'],
    ['Kapha Dosha', 'Avalambaka Kapha is located in the', ['Shira', 'Jihva', 'Uras', 'Sandhi'], 2, 'EASY', 'Avalambaka Kapha in the chest (Uras) supports the other Kapha sites.'],
    ['Kapha Dosha', 'Bodhaka Kapha helps in', ['Perception of taste', 'Lubrication of joints', 'Nourishing sense organs', 'Moistening food'], 0, 'EASY', 'Bodhaka Kapha in the tongue helps perceive taste.'],
    ['Kapha Dosha', 'Tarpaka Kapha is located in the', ['Uras', 'Shira', 'Amashaya', 'Kantha'], 1, 'MEDIUM', 'Tarpaka Kapha in the head nourishes the sense organs.'],
    ['Kapha Dosha', 'Shleshaka Kapha is located in the', ['Sandhi', 'Jihva', 'Amashaya', 'Hridaya'], 0, 'EASY', 'Shleshaka Kapha lubricates the joints.'],
    ['Dhatu', 'What are the Upadhatus of Rasa Dhatu?', ['Sira and Kandara', 'Stanya and Artava', 'Vasa and Snayu', 'Danta and Kesha'], 1, 'MEDIUM', 'Stanya (breast milk) and Artava are the Upadhatus of Rasa.'],
    ['Dhatu', 'The quantity of Para Ojas is', ['8 Bindu', 'Ardha Anjali', '1 Anjali', '2 Anjali'], 0, 'MEDIUM', 'Para Ojas is 8 Bindu and resides in the Hridaya; Apara Ojas is Ardha Anjali.'],
    ['Dhatu', 'According to Charaka, the quantity of Rakta (Shonita) in the body is', ['9 Anjali', '8 Anjali', '7 Anjali', '6 Anjali'], 1, 'HARD', 'Charaka Sharira 7: Rasa 9, Shonita 8, Purisha 7, Shleshma 6, Pitta 5 Anjali.'],
    ['Agni', 'What is the total number of Agnis?', ['5', '7', '13', '40'], 2, 'EASY', '1 Jatharagni + 5 Bhutagni + 7 Dhatvagni = 13.'],
    ['Prakriti', 'Deha Prakriti is decided at the time of', ['Birth', 'Shukra-Shonita Samyoga', 'The 5th month of pregnancy', 'Puberty'], 1, 'MEDIUM', 'The dominant Dosha at the union of Shukra and Shonita decides the Prakriti.'],
    ['Dhatu', 'How many Dhatus are described in Ayurveda?', ['5', '6', '7', '8'], 2, 'EASY', 'Rasa, Rakta, Mamsa, Meda, Asthi, Majja and Shukra.'],
  ],
  'Rachana Sharir': [
    ['Asthi', 'According to Sushruta, the number of Asthis is', ['206', '300', '360', '500'], 1, 'EASY', 'Sushruta counts 300 bones; Charaka counts 360 (including teeth and nails).'],
    ['Asthi', 'According to Charaka, the number of Asthis is', ['300', '320', '360', '206'], 2, 'EASY', 'Charaka counts 360, including teeth, their sockets and nails.'],
    ['Marma', 'What is the total number of Marmas?', ['100', '107', '108', '210'], 1, 'EASY', 'Sushruta describes 107 Marmas.'],
    ['Marma', 'How many Sadyapranahara Marmas are there?', ['19', '33', '44', '3'], 0, 'MEDIUM', 'There are 19 Sadyapranahara Marmas, injury to which kills quickly.'],
    ['Marma', 'Hridaya Marma belongs to which category?', ['Kalantara Pranahara', 'Sadyapranahara', 'Vaikalyakara', 'Rujakara'], 1, 'EASY', 'Hridaya, Shira and Basti are the Trimarma and are Sadyapranahara.'],
    ['Marma', 'Talahridaya Marma belongs to which category?', ['Sadyapranahara', 'Kalantara Pranahara', 'Vishalyaghna', 'Vaikalyakara'], 1, 'HARD', 'Talahridaya on the palm and sole is a Kalantara Pranahara Marma.'],
    ['Marma', 'How many Marmas are present in the four Shakhas (limbs)?', ['22', '44', '26', '37'], 1, 'MEDIUM', 'Each limb has 11 Marmas, so the four Shakhas have 44.'],
    ['Sandhi', 'According to Sushruta, the number of Sandhis is', ['107', '210', '300', '500'], 1, 'MEDIUM', 'Sushruta describes 210 Sandhis.'],
    ['Peshi', 'According to Sushruta, the number of Peshis in a male is', ['400', '500', '600', '900'], 1, 'MEDIUM', '500 Peshis in men; women have 20 more.'],
    ['Sira-Dhamani', 'According to Sushruta, the number of Siras is', ['24', '200', '700', '900'], 2, 'MEDIUM', 'Sushruta describes 700 Siras; Dhamanis are 24.'],
    ['Sira-Dhamani', 'The number of Dhamanis described by Sushruta is', ['10', '24', '40', '56'], 1, 'EASY', '24 Dhamanis arise from the Nabhi.'],
    ['Twak', 'According to Sushruta, Twak has how many layers?', ['5', '6', '7', '8'], 2, 'EASY', 'Sushruta describes 7 layers of skin; Charaka describes 6.'],
    ['Kala', 'How many Kalas are described?', ['5', '7', '9', '12'], 1, 'EASY', 'Seven Kalas, from Mamsadhara to Shukradhara.'],
    ['Koshtha', 'According to Charaka, the number of Koshthangas is', ['8', '12', '15', '18'], 2, 'HARD', 'Charaka Sharira 7 lists 15 Koshthangas.'],
  ],
  Dravyaguna: [
    ['Rasa', 'How many Rasas are described in Ayurveda?', ['5', '6', '7', '8'], 1, 'EASY', 'Madhura, Amla, Lavana, Katu, Tikta and Kashaya.'],
    ['Rasa', 'Katu Rasa is made of which Mahabhutas?', ['Prithvi + Jala', 'Vayu + Agni', 'Agni + Jala', 'Vayu + Akasha'], 1, 'MEDIUM', 'Katu: Vayu + Agni. Tikta: Vayu + Akasha. Kashaya: Vayu + Prithvi.'],
    ['Rasa', 'Tikta Rasa is made of which Mahabhutas?', ['Vayu + Akasha', 'Prithvi + Agni', 'Jala + Agni', 'Prithvi + Jala'], 0, 'MEDIUM', 'Tikta Rasa has a predominance of Vayu and Akasha.'],
    ['Rasa', 'Lavana Rasa is made of which Mahabhutas?', ['Prithvi + Agni', 'Jala + Agni', 'Vayu + Prithvi', 'Prithvi + Jala'], 1, 'MEDIUM', 'Lavana: Jala + Agni (Charaka).'],
    ['Vipaka', 'According to Charaka, how many Vipakas are there?', ['2', '3', '5', '6'], 1, 'EASY', 'Madhura, Amla and Katu Vipaka.'],
    ['Virya', 'According to most Acharyas, Virya is of how many types?', ['2', '3', '6', '8'], 0, 'EASY', 'Ushna and Shita Virya.'],
    ['Dravya', 'The botanical name of Haritaki is', ['Terminalia bellirica', 'Terminalia chebula', 'Terminalia arjuna', 'Phyllanthus emblica'], 1, 'EASY', 'Haritaki is Terminalia chebula; Bibhitaki is T. bellirica.'],
    ['Dravya', 'The botanical name of Guduchi is', ['Tinospora cordifolia', 'Withania somnifera', 'Bacopa monnieri', 'Asparagus racemosus'], 0, 'EASY', 'Guduchi (Amrita) is Tinospora cordifolia.'],
    ['Dravya', 'Ashwagandha is', ['Withania somnifera', 'Tinospora cordifolia', 'Centella asiatica', 'Embelia ribes'], 0, 'EASY', 'Ashwagandha is Withania somnifera, a well known Rasayana.'],
    ['Dravya', 'Haridra belongs to which family?', ['Zingiberaceae', 'Liliaceae', 'Fabaceae', 'Apiaceae'], 0, 'MEDIUM', 'Curcuma longa belongs to Zingiberaceae.'],
    ['Dravya', 'Arjuna is mainly used in', ['Hridroga', 'Kushtha', 'Prameha', 'Arsha'], 0, 'EASY', 'Arjuna bark is the classical Hridya drug.'],
    ['Gana', 'Triphala consists of', ['Shunthi, Maricha, Pippali', 'Haritaki, Bibhitaki, Amalaki', 'Guduchi, Amalaki, Gokshura', 'Bilva, Agnimantha, Patala'], 1, 'EASY', 'Triphala: Haritaki, Bibhitaki and Amalaki.'],
    ['Gana', 'Trikatu consists of', ['Shunthi, Maricha, Pippali', 'Haritaki, Bibhitaki, Amalaki', 'Ela, Twak, Patra', 'Chitraka, Danti, Trivrit'], 0, 'EASY', 'Trikatu: Shunthi, Maricha and Pippali.'],
    ['Gana', 'Which of these belongs to Brihat Panchamoola?', ['Shalaparni', 'Bilva', 'Brihati', 'Gokshura'], 1, 'MEDIUM', 'Brihat Panchamoola: Bilva, Agnimantha, Shyonaka, Patala, Gambhari.'],
    ['Gana', 'How many Mahakashayas are described by Charaka?', ['37', '45', '50', '60'], 2, 'MEDIUM', 'Charaka Sutrasthana 4 describes 50 Mahakashayas of 10 drugs each.'],
    ['Gana', 'How many Ganas are described by Sushruta?', ['37', '50', '41', '24'], 0, 'HARD', 'Sushruta Sutrasthana 38 describes 37 Ganas.'],
  ],
  'Rasa Shastra': [
    ['Parada', 'How many Samskaras of Parada are described?', ['8', '12', '18', '24'], 2, 'EASY', 'Eighteen Samskaras; the first eight are used for therapeutic Parada.'],
    ['Parada', 'Hingula is an ore of', ['Gandhaka', 'Parada', 'Naga', 'Vanga'], 1, 'EASY', 'Hingula (cinnabar, HgS) is the ore from which Parada is extracted.'],
    ['Parada', 'Kajjali is prepared from', ['Parada and Gandhaka', 'Parada and Hingula', 'Gandhaka and Tankana', 'Abhraka and Parada'], 0, 'EASY', 'Kajjali is the black mixture of Parada and Gandhaka triturated together.'],
    ['Maharasa', 'Shilajatu is grouped under', ['Uparasa', 'Maharasa', 'Sadharana Rasa', 'Ratna'], 1, 'HARD', 'Rasa Ratna Samuchchaya groups Shilajatu with the Maharasas.'],
    ['Maharasa', 'Abhraka is', ['Mica', 'Talc', 'Gypsum', 'Calcite'], 0, 'EASY', 'Abhraka is mica.'],
    ['Maharasa', 'Swarna Makshika is', ['Iron pyrite', 'Copper pyrite (chalcopyrite)', 'Galena', 'Zinc blende'], 1, 'MEDIUM', 'Swarna Makshika is chalcopyrite (copper iron sulphide).'],
    ['Uparasa', 'Tankana is', ['Alum', 'Borax', 'Rock salt', 'Saltpetre'], 1, 'EASY', 'Tankana is borax; Sphatika is alum.'],
    ['Uparasa', 'Manahshila is', ['Orpiment', 'Realgar', 'Cinnabar', 'Stibnite'], 1, 'MEDIUM', 'Manahshila is realgar (As4S4); Haratala is orpiment (As2S3).'],
    ['Uparasa', 'Haratala is', ['Realgar', 'Orpiment', 'Galena', 'Red ochre'], 1, 'MEDIUM', 'Haratala is orpiment (arsenic trisulphide).'],
  ],
  Kayachikitsa: [
    ['Prameha', 'According to Charaka, how many types of Prameha are there?', ['10', '20', '18', '8'], 1, 'EASY', '10 Kaphaja, 6 Pittaja and 4 Vataja: 20 Pramehas.'],
    ['Kushtha', 'How many types of Kushtha are described?', ['7', '11', '18', '20'], 2, 'EASY', '7 Mahakushtha and 11 Kshudrakushtha.'],
    ['Jwara', 'Based on Doshas, Jwara is of how many types?', ['5', '7', '8', '13'], 2, 'MEDIUM', 'Vataja, Pittaja, Kaphaja, three Dvandvaja, Sannipataja and Agantuja: 8.'],
    ['Pandu', 'According to Charaka, Pandu Roga is of how many types?', ['4', '5', '6', '8'], 1, 'EASY', 'Vataja, Pittaja, Kaphaja, Sannipataja and Mrittikabhakshanaja.'],
    ['Kasa-Shwasa', 'How many types of Shwasa are described?', ['3', '5', '6', '8'], 1, 'EASY', 'Maha, Urdhva, Chhinna, Tamaka and Kshudra Shwasa.'],
    ['Kasa-Shwasa', 'How many types of Kasa are described?', ['3', '4', '5', '6'], 2, 'EASY', 'Vataja, Pittaja, Kaphaja, Kshataja and Kshayaja.'],
    ['Udara', 'How many types of Udara Roga are described?', ['5', '6', '8', '10'], 2, 'MEDIUM', 'Eight Udara Rogas, including Jalodara.'],
    ['Atisara', 'According to Charaka, Atisara is of how many types?', ['4', '5', '6', '8'], 2, 'MEDIUM', 'Vataja, Pittaja, Kaphaja, Sannipataja, Bhayaja and Shokaja.'],
    ['Amavata', 'Amavata was first described as a separate disease by', ['Charaka', 'Sushruta', 'Madhavakara', 'Vagbhata'], 2, 'MEDIUM', 'Madhava Nidana chapter 25 first describes Amavata as a separate disease.'],
    ['Vatavyadhi', 'How many Nanatmaja Vata Vikaras are described by Charaka?', ['20', '40', '80', '100'], 2, 'EASY', '80 Vataja, 40 Pittaja and 20 Kaphaja Nanatmaja Vikaras.'],
    ['Vatavyadhi', 'How many Nanatmaja Kapha Vikaras are described?', ['20', '40', '80', '10'], 0, 'MEDIUM', 'Charaka Sutrasthana 20 lists 20 Kaphaja Nanatmaja Vikaras.'],
    ['Rajayakshma', 'The Ekadasha Rupa (11 symptoms) are described for', ['Rajayakshma', 'Pandu', 'Kamala', 'Unmada'], 0, 'MEDIUM', 'Rajayakshma has Trirupa, Shadrupa and Ekadasha Rupa presentations.'],
    ['Manasa Roga', 'According to Charaka, Apasmara is of how many types?', ['3', '4', '5', '8'], 1, 'MEDIUM', 'Vataja, Pittaja, Kaphaja and Sannipataja Apasmara.'],
    ['Manasa Roga', 'According to Charaka, Unmada is of how many types?', ['4', '5', '6', '8'], 1, 'MEDIUM', 'Vataja, Pittaja, Kaphaja, Sannipataja and Agantuja Unmada.'],
    ['Arsha', 'According to Sushruta, Arsha is of how many types?', ['4', '5', '6', '8'], 2, 'MEDIUM', 'Six types: Vataja, Pittaja, Kaphaja, Sannipataja, Raktaja and Sahaja.'],
  ],
  Panchakarma: [
    ['Shodhana', 'Vamana is the best treatment for', ['Vata', 'Pitta', 'Kapha', 'Rakta'], 2, 'EASY', 'Vamana for Kapha, Virechana for Pitta and Basti for Vata.'],
    ['Shodhana', 'Virechana is the best treatment for', ['Vata', 'Pitta', 'Kapha', 'Meda'], 1, 'EASY', 'Virechana is the prime Shodhana for Pitta.'],
    ['Shodhana', 'Which is the best Vamaka dravya?', ['Trivrit', 'Madanaphala', 'Eranda', 'Danti'], 1, 'EASY', 'Madanaphala is the Shreshtha Vamaka; Trivrit is the Shreshtha Virechaka.'],
    ['Basti', 'How many Bastis are given in Karma Basti?', ['8', '16', '30', '15'], 2, 'EASY', 'Karma Basti 30, Kala Basti 16, Yoga Basti 8.'],
    ['Basti', 'How many Bastis are given in Kala Basti?', ['8', '16', '30', '12'], 1, 'EASY', 'Kala Basti is a course of 16 Bastis.'],
    ['Basti', 'Matra Basti is a type of', ['Niruha Basti', 'Sneha Basti', 'Uttara Basti', 'Kshira Basti'], 1, 'MEDIUM', 'Matra Basti is a small-dose Anuvasana (Sneha) Basti that can be given daily.'],
    ['Nasya', 'Nasya should not be given below the age of', ['5 years', '7 years', '12 years', '16 years'], 1, 'MEDIUM', 'Nasya is indicated from 7 to 80 years of age.'],
    ['Snehana', 'Acchapana means', ['Sneha taken alone', 'Sneha mixed with food', 'Sneha given as Basti', 'Sneha applied on skin'], 0, 'EASY', 'Acchapana is drinking pure Sneha without mixing it with food.'],
    ['Samsarjana', 'After Pravara Shuddhi, Samsarjana Krama is followed for', ['3 days', '5 days', '7 days', '10 days'], 2, 'MEDIUM', 'Pravara 7 days, Madhyama 5 days and Avara 3 days.'],
    ['Murdha Taila', 'Shirodhara is a type of', ['Nasya', 'Murdha Taila', 'Gandusha', 'Anjana'], 1, 'EASY', 'Murdha Taila: Shiro Abhyanga, Shiro Pichu, Shiro Seka (Dhara) and Shiro Basti.'],
  ],
  'Shalya Tantra': [
    ['Yantra-Shastra', 'According to Sushruta, the number of Yantras is', ['20', '60', '101', '107'], 2, 'EASY', 'Sushruta describes 101 blunt instruments (Yantras).'],
    ['Yantra-Shastra', 'According to Sushruta, the number of Shastras is', ['20', '24', '101', '8'], 0, 'EASY', 'Twenty sharp instruments (Shastras).'],
    ['Yantra-Shastra', 'Which is considered the best (Pradhana) Yantra?', ['Kankamukha', 'Hasta', 'Sandamsha', 'Shalaka'], 1, 'MEDIUM', 'The hand (Hasta) is the best Yantra, since every other Yantra works through it.'],
    ['Yantra-Shastra', 'Kankamukha is the best among', ['Swastika Yantras', 'Sandamsha Yantras', 'Nadi Yantras', 'Shalaka Yantras'], 0, 'MEDIUM', 'Kankamukha is the Shreshtha Swastika Yantra.'],
    ['Kshara', 'Kshara is of how many types by use?', ['2', '3', '4', '5'], 0, 'EASY', 'Pratisaraniya (external) and Paniya (internal).'],
    ['Kshara', 'Ksharasutra is mainly used in the treatment of', ['Arsha', 'Bhagandara', 'Ashmari', 'Granthi'], 1, 'EASY', 'Ksharasutra is the classical treatment of Bhagandara (fistula in ano).'],
    ['Kshara', 'A standard Ksharasutra has how many coatings in total?', ['11', '18', '21', '7'], 2, 'HARD', '11 coats of Snuhi latex, 7 of Snuhi + Apamarga Kshara and 3 of Snuhi + Haridra.'],
    ['Raktamokshana', 'How many types of Jalauka (leeches) are described by Sushruta?', ['6', '10', '12', '18'], 2, 'MEDIUM', '6 Savisha and 6 Nirvisha: 12 Jalaukas.'],
    ['Vrana', 'How many Upakramas of Vrana are described by Sushruta?', ['36', '50', '60', '64'], 2, 'EASY', 'Shashti Upakrama: 60 measures for the treatment of wounds.'],
    ['Shastra Karma', 'How many Shastra Karmas are described?', ['6', '8', '10', '12'], 1, 'EASY', 'Ashtavidha Shastra Karma: Chhedana, Bhedana, Lekhana, Vedhana, Eshana, Aharana, Visravana, Seevana.'],
    ['Anorectal', 'According to Sushruta, Bhagandara is of how many types?', ['4', '5', '6', '8'], 1, 'MEDIUM', 'Shataponaka, Ushtragriva, Parisravi, Shambukavarta and Unmargi.'],
    ['Mutraroga', 'According to Sushruta, Ashmari is of how many types?', ['3', '4', '5', '6'], 1, 'MEDIUM', 'Vataja, Pittaja, Kaphaja and Shukraja Ashmari.'],
    ['Bhagna', 'Bhagna is broadly of how many types?', ['2', '4', '6', '12'], 0, 'EASY', 'Sandhimukta (dislocation) and Kandabhagna (fracture).'],
  ],
  'Prasuti Tantra': [
    ['Stri Roga', 'According to Charaka, how many Yonivyapads are there?', ['8', '12', '20', '24'], 2, 'EASY', 'Twenty Yonivyapads are described in Charaka Chikitsa 30.'],
    ['Garbha', 'Dauhrida appears in which month of pregnancy?', ['2nd', '3rd', '4th', '6th'], 2, 'MEDIUM', 'In the 4th month the Hridaya of the foetus is manifest, so the mother has Dauhrida.'],
    ['Sutika', 'The Sutika Kala is', ['15 days', '1 month', '1.5 months', '3 months'], 2, 'EASY', 'The puerperal period is one and a half months (about 45 days).'],
    ['Stanya', 'Pure Stanya is tested by', ['Jala Pariksha', 'Agni Pariksha', 'Taila Bindu', 'Kshara Pariksha'], 0, 'MEDIUM', 'Pure breast milk mixes evenly with water (Jala Pariksha).'],
    ['Rajaswala', 'Rajaswala Charya is followed for', ['3 days', '5 days', '7 days', '1 day'], 0, 'MEDIUM', 'Rajaswala Paricharya is advised for the first three days of menstruation.'],
  ],
  Kaumarbhritya: [
    ['Classics', 'Kashyapa Samhita mainly deals with', ['Shalya', 'Kaumarbhritya', 'Rasayana', 'Agada'], 1, 'EASY', 'Kashyapa Samhita is the classical text of Kaumarbhritya.'],
    ['Classics', 'Kashyapa Samhita is also known as', ['Vriddha Jivakiya Tantra', 'Bhela Samhita', 'Harita Samhita', 'Ashtanga Sangraha'], 0, 'MEDIUM', 'It was narrated to Vriddha Jivaka, hence Vriddha Jivakiya Tantra.'],
    ['Balaroga', 'Phakka Roga is described by', ['Charaka', 'Sushruta', 'Kashyapa', 'Madhava'], 2, 'MEDIUM', 'Kashyapa describes Phakka, a nutritional disorder of children who cannot walk.'],
    ['Balaroga', 'According to Sushruta, how many Balagrahas are there?', ['7', '9', '12', '18'], 1, 'HARD', 'Sushruta Uttaratantra describes nine Balagrahas.'],
  ],
  Swasthavritta: [
    ['Ritucharya', 'Which Ritus form the Visarga Kala?', ['Shishira, Vasanta, Grishma', 'Varsha, Sharad, Hemanta', 'Vasanta, Varsha, Sharad', 'Hemanta, Shishira, Vasanta'], 1, 'EASY', 'Visarga (Dakshinayana): Varsha, Sharad, Hemanta. Adana: Shishira, Vasanta, Grishma.'],
    ['Ritucharya', 'Vamana is advised in which Ritu?', ['Varsha', 'Sharad', 'Vasanta', 'Hemanta'], 2, 'EASY', 'Vamana in Vasanta, Virechana in Sharad and Basti in Varsha.'],
    ['Ritucharya', 'Ritu Sandhi lasts for', ['7 days', '14 days', '21 days', '1 month'], 1, 'MEDIUM', 'The last 7 days of one Ritu and the first 7 of the next: 14 days.'],
    ['Dinacharya', 'Trayopastambha consists of', ['Vata, Pitta, Kapha', 'Ahara, Nidra, Brahmacharya', 'Satva, Atma, Sharira', 'Rasa, Rakta, Mamsa'], 1, 'EASY', 'Ahara, Nidra and Brahmacharya are the three sub-pillars of life.'],
    ['Vega', 'How many Adharaniya Vegas are described by Charaka?', ['10', '13', '14', '18'], 1, 'EASY', 'Thirteen natural urges must not be suppressed.'],
    ['Ahara', 'According to Charaka, how many types of Viruddha Ahara are there?', ['8', '12', '18', '20'], 2, 'MEDIUM', 'Charaka Sutrasthana 26 lists 18 kinds of incompatibility.'],
    ['Nidra', 'According to Charaka, Nidra is of how many types?', ['3', '5', '7', '9'], 2, 'MEDIUM', 'Charaka Sutrasthana 21 describes seven types of sleep.'],
  ],
  Samhita: [
    ['Charaka Samhita', 'How many Sthanas are there in Charaka Samhita?', ['6', '7', '8', '9'], 2, 'EASY', 'Eight Sthanas with 120 Adhyayas.'],
    ['Charaka Samhita', 'Who completed the Charaka Samhita?', ['Chakrapani', 'Dridhabala', 'Jejjata', 'Vagbhata'], 1, 'EASY', 'Dridhabala added the missing chapters and completed the Samhita.'],
    ['Charaka Samhita', 'How many chapters were added by Dridhabala?', ['17', '24', '41', '51'], 2, 'MEDIUM', '17 of Chikitsasthana plus the whole Kalpa (12) and Siddhi (12) Sthanas.'],
    ['Charaka Samhita', 'Ayurveda Dipika is a commentary on Charaka Samhita by', ['Dalhana', 'Chakrapanidatta', 'Arunadatta', 'Gangadhara'], 1, 'EASY', 'Chakrapanidatta wrote Ayurveda Dipika.'],
    ['Charaka Samhita', 'The Guru of Agnivesha was', ['Divodasa Dhanvantari', 'Punarvasu Atreya', 'Kashyapa', 'Bharadvaja'], 1, 'EASY', 'Agnivesha learned from Punarvasu Atreya.'],
    ['Sushruta Samhita', 'Nibandha Sangraha is a commentary on Sushruta Samhita by', ['Dalhana', 'Chakrapani', 'Hemadri', 'Indu'], 0, 'EASY', 'Dalhana wrote Nibandha Sangraha.'],
    ['Sushruta Samhita', 'The Guru of Sushruta was', ['Punarvasu Atreya', 'Divodasa Dhanvantari', 'Kashyapa', 'Agnivesha'], 1, 'EASY', 'Sushruta learned from Divodasa Dhanvantari, king of Kashi.'],
    ['Ashtanga Hridaya', 'Ashtanga Hridaya was written by', ['Vagbhata', 'Madhavakara', 'Sharngadhara', 'Bhavamishra'], 0, 'EASY', 'Ashtanga Hridaya is by Vagbhata.'],
    ['Ashtanga Hridaya', 'Sarvangasundara is a commentary on Ashtanga Hridaya by', ['Hemadri', 'Arunadatta', 'Indu', 'Dalhana'], 1, 'MEDIUM', 'Arunadatta wrote Sarvangasundara; Hemadri wrote Ayurveda Rasayana.'],
    ['Laghutrayi', 'How many Khandas are there in Sharngadhara Samhita?', ['2', '3', '4', '6'], 1, 'EASY', 'Purva, Madhyama and Uttara Khanda.'],
    ['Laghutrayi', 'Bhavaprakasha was written by', ['Bhavamishra', 'Madhavakara', 'Sharngadhara', 'Yogaratnakara'], 0, 'EASY', 'Bhavaprakasha is by Bhavamishra (16th century).'],
    ['Charaka Samhita', 'How many branches (Angas) does Ashtanga Ayurveda have?', ['6', '7', '8', '10'], 2, 'EASY', 'Kaya, Bala, Graha, Urdhvanga, Shalya, Damshtra, Jara and Vrisha.'],
  ],
};

/** Which subjects each demo course teaches (its question bank, notes and doubts follow from this). */
export const COURSES = [
  {
    key: 'aiapget',
    name: 'AIAPGET 2027 Complete Preparation',
    description: 'Full syllabus preparation for the All India AYUSH Post Graduate Entrance Test, with daily live classes and weekly mock tests.',
    tagline: 'Concept-first coaching for the AYUSH PG entrance, with weekly mock tests in the real exam pattern',
    language: 'Hindi + English',
    duration: '10 months',
    highlights: [
      'Every subject of the BAMS syllabus, revised for the PG entrance',
      'Weekly mock tests in the AIAPGET pattern (+4 / -1)',
      'Samhita references for every important topic',
      'Previous year questions solved and explained',
      'Rank and subject-wise analysis after every test',
    ],
    includes: ['Daily live classes', 'Recorded lectures', 'Subject-wise PDF notes', '40+ mock and unit tests'],
    audience: ['BAMS final year students and interns', 'BAMS graduates preparing for MD/MS (Ayurveda)'],
    faqs: [
      { q: 'Are the classes recorded?', a: 'Yes. Every live class is recorded and available in the app for the rest of the course.' },
      { q: 'Is the test series included?', a: 'Yes. Weekly mock tests and unit tests are part of the course.' },
    ],
    subjects: ['Padartha Vigyan', 'Kriya Sharir', 'Rachana Sharir', 'Dravyaguna', 'Rasa Shastra', 'Kayachikitsa', 'Panchakarma', 'Shalya Tantra', 'Prasuti Tantra', 'Kaumarbhritya', 'Swasthavritta', 'Samhita'],
    batches: [
      { name: 'AIAPGET 2027: Morning Batch', start: '2026-08-01', end: '2027-05-31' },
      { name: 'AIAPGET 2027: Weekend Batch', start: '2026-09-06', end: '2027-05-31' },
    ],
    plan: { name: 'AIAPGET 2027: Full Course', total: 14999, mrp: 24999, offer: { price: 11999, label: 'Diwali offer', ends: '2026-10-25T23:59:59+05:30' } },
  },
  {
    key: 'amo',
    name: 'AMO Exam Preparation',
    description: 'Preparation for State and Central Ayurveda Medical Officer exams, by a teacher who has cleared the AMO exam six times.',
    tagline: 'Crack the State and Central AMO exams with focused classes and exam-pattern practice',
    language: 'Hindi + English',
    duration: '6 months',
    highlights: [
      'Complete AMO syllabus: Samhita, Kayachikitsa, Shalya, Dravyaguna and more',
      'State-wise previous papers discussed',
      'Short notes for last-month revision',
      'Practice tests with negative marking',
    ],
    includes: ['Live classes 5 days a week', 'PDF notes', 'Practice and grand tests'],
    audience: ['BAMS graduates preparing for State or Central AMO exams'],
    faqs: [{ q: 'Which exams does this cover?', a: 'HPPSC, UKPSC, RPSC and other State AMO exams, and central AMO recruitments.' }],
    subjects: ['Samhita', 'Kayachikitsa', 'Panchakarma', 'Shalya Tantra', 'Dravyaguna', 'Swasthavritta'],
    batches: [{ name: 'AMO 2026-27 Batch', start: '2026-07-15', end: '2027-01-31' }],
    plan: { name: 'AMO Exam: Full Course', total: 9999, mrp: 14999 },
  },
  {
    key: 'bams1',
    name: 'BAMS 1st Prof Coaching',
    description: 'Semester support for first professional BAMS: Padartha Vigyan, Kriya Sharir, Rachana Sharir and Samhita.',
    tagline: 'Build strong basics in your first year of BAMS',
    language: 'Hindi + English',
    duration: '12 months',
    highlights: ['Every 1st Prof subject explained from the basics', 'Unit tests after each chapter', 'Exam-oriented notes'],
    includes: ['Live classes 3 days a week', 'PDF notes', 'Unit tests'],
    audience: ['BAMS first professional students'],
    faqs: [],
    subjects: ['Padartha Vigyan', 'Kriya Sharir', 'Rachana Sharir', 'Samhita'],
    batches: [{ name: 'BAMS 1st Prof 2026', start: '2026-08-10', end: '2027-07-31' }],
    plan: { name: 'BAMS 1st Prof: Yearly', total: 5999, mrp: 7999 },
  },
  {
    key: 'bamsfinal',
    name: 'BAMS Final Prof Coaching',
    description: 'Final year support for Shalya, Kayachikitsa, Panchakarma and Prasuti Tantra, with case-based teaching.',
    tagline: 'Clinical subjects taught the way they are practised',
    language: 'Hindi + English',
    duration: '12 months',
    highlights: ['Case-based classes from 15 years of clinical surgery', 'Viva and practical exam guidance', 'Unit tests'],
    includes: ['Live classes 3 days a week', 'PDF notes', 'Unit tests'],
    audience: ['BAMS final professional students'],
    faqs: [],
    subjects: ['Shalya Tantra', 'Kayachikitsa', 'Panchakarma', 'Prasuti Tantra'],
    batches: [{ name: 'BAMS Final 2026', start: '2026-08-10', end: '2027-07-31' }],
    plan: { name: 'BAMS Final Prof: Yearly', total: 6999 },
  },
] as const;

/** Short notes turned into PDFs: [subject, topic, title, paragraphs]. */
export const NOTES: [string, string, string, string[]][] = [
  ['Kriya Sharir', 'Vata Dosha', 'Tridosha: Five types of Vata', [
    'Vata is the moving principle of the body. It is Ruksha, Laghu, Shita, Khara, Sukshma and Chala.',
    'Prana Vayu: seat Murdha; governs breathing, swallowing, the senses and the mind.',
    'Udana Vayu: seat Uras; governs speech, effort, energy, strength and memory.',
    'Samana Vayu: near the Agni; holds food in the Amashaya, digests it, separates Sara and Kitta.',
    'Vyana Vayu: seat Hridaya, moves through the whole body; governs circulation and movement.',
    'Apana Vayu: seat Pakvashaya; governs elimination of stool, urine, semen, menses and the foetus.',
    'Exam tip: learn the Sthana and Karma of each type as a table; both are asked every year.',
  ]],
  ['Kriya Sharir', 'Pitta Dosha', 'Tridosha: Five types of Pitta', [
    'Pachaka Pitta: between Amashaya and Pakvashaya; digests food and supports the other Pittas.',
    'Ranjaka Pitta: gives colour to Rasa and turns it into Rakta.',
    'Sadhaka Pitta: in the Hridaya; supports intellect, memory and self-esteem.',
    'Alochaka Pitta: in the eyes; responsible for vision.',
    'Bhrajaka Pitta: in the skin; gives lustre and digests substances applied to the skin.',
  ]],
  ['Rachana Sharir', 'Marma', 'Marma Sharira: classification and numbers', [
    'Sushruta describes 107 Marmas: 44 in the Shakhas, 26 in the trunk and 37 in the head and neck.',
    'By effect of injury: Sadyapranahara 19, Kalantara Pranahara 33, Vishalyaghna 3, Vaikalyakara 44, Rujakara 8.',
    'By structure: Mamsa, Sira, Snayu, Asthi and Sandhi Marmas.',
    'Trimarma: Hridaya, Shira and Basti. All three are Sadyapranahara.',
  ]],
  ['Padartha Vigyan', 'Pramana', 'Pramana Vigyan at a glance', [
    'Charaka accepts four Pramanas for examination: Aptopadesha, Pratyaksha, Anumana and Yukti.',
    'Sushruta accepts four: Aptopadesha, Pratyaksha, Anumana and Upamana.',
    'Yukti is the reasoning that sees how many factors combine to produce an effect, for example the growth of a crop.',
  ]],
  ['Dravyaguna', 'Rasa', 'Shad Rasa and their Mahabhutas', [
    'Madhura: Prithvi + Jala. Amla: Prithvi + Agni. Lavana: Jala + Agni.',
    'Katu: Vayu + Agni. Tikta: Vayu + Akasha. Kashaya: Vayu + Prithvi.',
    'Vipaka: Madhura for Madhura and Lavana; Amla for Amla; Katu for Katu, Tikta and Kashaya.',
  ]],
  ['Kayachikitsa', 'Prameha', 'Prameha: types and management', [
    'Charaka describes 20 Pramehas: 10 Kaphaja, 6 Pittaja and 4 Vataja.',
    'Kaphaja types are Sadhya, Pittaja are Yapya and Vataja are Asadhya.',
    'Management: Apatarpana for the strong and obese, Santarpana for the weak; Shodhana followed by Shamana.',
  ]],
  ['Panchakarma', 'Basti', 'Basti Karma: schedules', [
    'Karma Basti: 30 Bastis (12 Niruha and 18 Anuvasana).',
    'Kala Basti: 16 Bastis (6 Niruha and 10 Anuvasana).',
    'Yoga Basti: 8 Bastis (3 Niruha and 5 Anuvasana).',
    'Matra Basti is a small-dose Anuvasana Basti that can be given daily, even to the weak and elderly.',
  ]],
  ['Shalya Tantra', 'Kshara', 'Ksharasutra in Bhagandara', [
    'A Ksharasutra is a surgical thread coated 21 times: 11 coats of Snuhi latex, 7 of Snuhi with Apamarga Kshara and 3 of Snuhi with Haridra powder.',
    'It cuts and heals the fistulous tract at the same time, with a low recurrence rate.',
    'The thread is changed every week until the tract is cut through.',
  ]],
  ['Samhita', 'Charaka Samhita', 'Brihattrayi: authors and commentators', [
    'Charaka Samhita: Agnivesha Tantra redacted by Charaka and completed by Dridhabala. Commentary: Ayurveda Dipika by Chakrapanidatta.',
    'Sushruta Samhita: commentary Nibandha Sangraha by Dalhana.',
    'Ashtanga Hridaya: by Vagbhata. Commentaries: Sarvangasundara by Arunadatta, Ayurveda Rasayana by Hemadri.',
  ]],
  ['Swasthavritta', 'Ritucharya', 'Ritucharya and Shodhana calendar', [
    'Adana Kala: Shishira, Vasanta, Grishma. Visarga Kala: Varsha, Sharad, Hemanta.',
    'Vamana in Vasanta, Virechana in Sharad and Basti in Varsha.',
    'Ritu Sandhi: the last 7 days of one Ritu and the first 7 days of the next.',
  ]],
];

/** Doubt threads: [subject, question title, student message, teacher reply, resolved?]. */
export const DOUBTS: [string, string, string, string | null, boolean][] = [
  ['Kriya Sharir', 'Difference between Sadhaka and Alochaka Pitta', 'Sir, both are Pitta, so why is one in the Hridaya and the other in the eyes? How do I remember their Karmas?', 'Sadhaka Pitta works on the mind (Buddhi, Medha, Abhimana), so it sits in the Hridaya, the seat of Chetana. Alochaka works on vision, so it sits in the eyes. Remember: Sadhaka = sadhana of goals, Alochaka = alochana (seeing).', true],
  ['Rachana Sharir', 'Why is Talahridaya Kalantara Pranahara?', 'Sir, Talahridaya has the word Hridaya in it but it is not Sadyapranahara. Why?', 'Its name only refers to its place in the centre of the palm or sole. It is a Mamsa Marma, and injury causes death after some time because of pain and bleeding, so it is Kalantara Pranahara.', true],
  ['Dravyaguna', 'Vipaka of Lavana Rasa', 'Is the Vipaka of Lavana Rasa Madhura or Amla? Different books give different answers.', 'Charaka says Madhura Vipaka for both Madhura and Lavana Rasa. Sushruta accepts only two Vipakas (Guru and Laghu). For AIAPGET follow Charaka: Lavana gives Madhura Vipaka.', true],
  ['Panchakarma', 'Karma Basti sequence', 'Sir, in Karma Basti does it start with Anuvasana or Niruha?', 'It starts with Anuvasana, then Niruha and Anuvasana alternate, and it ends with Anuvasana. Total 30: 12 Niruha and 18 Anuvasana.', false],
  ['Shalya Tantra', 'Ksharasutra change interval', 'How often should the Ksharasutra be changed in Bhagandara?', 'Once a week. The cutting rate is roughly 0.5 to 1 cm per week, so the number of changes depends on the length of the tract.', true],
  ['Samhita', 'Chapters added by Dridhabala', 'Sir, exactly which chapters did Dridhabala add?', 'The last 17 chapters of Chikitsasthana and all of Kalpa and Siddhi Sthana (12 each): 41 chapters in total.', false],
  ['Kayachikitsa', 'Sadhyasadhyata of Prameha', 'Which type of Prameha is Yapya?', null, false],
  ['Padartha Vigyan', 'Pilupaka and Pitharapaka', 'What is the difference between Pilupaka and Pitharapaka Vada?', null, false],
  ['Swasthavritta', 'Shodhana in Ritu Sandhi', 'Can Vamana be done during Ritu Sandhi?', 'Yes. Ritu Sandhi is a good time to start the regimen of the coming Ritu, and the Shodhana due in that Ritu can be planned then.', false],
];

export const FIRST_NAMES_M = ['Aman', 'Rohit', 'Vikas', 'Ankit', 'Sahil', 'Karan', 'Deepak', 'Nitin', 'Arjun', 'Varun', 'Gaurav', 'Rahul', 'Abhishek', 'Manish', 'Pankaj', 'Ajay', 'Sumit', 'Yash', 'Harsh', 'Tarun'];
export const FIRST_NAMES_F = ['Priya', 'Neha', 'Pooja', 'Anjali', 'Shruti', 'Kavita', 'Simran', 'Ritika', 'Sakshi', 'Megha', 'Nisha', 'Aarti', 'Divya', 'Komal', 'Tanvi', 'Shivani', 'Pallavi', 'Isha', 'Swati', 'Muskan'];
export const LAST_NAMES = ['Sharma', 'Thakur', 'Verma', 'Chauhan', 'Rana', 'Kumar', 'Guleria', 'Kaushal', 'Negi', 'Katoch', 'Sood', 'Bhardwaj', 'Pathania', 'Dogra', 'Mehta', 'Singh', 'Kapoor', 'Saini'];
export const CITIES = ['Bilaspur', 'Shimla', 'Mandi', 'Hamirpur', 'Kangra', 'Una', 'Solan', 'Kullu', 'Chandigarh', 'Ludhiana', 'Paprola', 'Dharamshala'];
